name: Build docker image and push to Amazon ECR

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  AWS_REGION: eu-central-1

permissions:
  id-token: write
  contents: read

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
 
    - name: Set AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::615677714887:role/personal-mehrshad-webpage-role
        aws-region: ${{ env.AWS_REGION }}
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2
    
    - name: Build, tag, and push docker image to Amazon ECR
      uses: docker/build-push-action@v5
      with:
        context: src
        build-args: |
          UPSTASH_REDIS_REST_TOKEN=${{ secrets.UPSTASH_REDIS_REST_TOKEN }}
          UPSTASH_REDIS_REST_URL=${{ secrets.UPSTASH_REDIS_REST_URL }}
        push: true
        tags: "615677714887.dkr.ecr.eu-central-1.amazonaws.com/personal-mehrshad-webpage-repo"
        cache-from: type=gha
        cache-to: type=gha,mode=max